name: music_playlist_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  dio: ^5.3.3
  cached_network_image: ^3.3.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  flutter_screenutil: ^5.9.0
  intl: ^0.18.1
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.6.0
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  scrollable_positioned_list: ^0.3.8
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env.development
    - .env.staging
    - .env.production
    - assets/icons/
